#include <QtGui/QApplication>
#include <QTextCodec>
#include <email.h>
#include <email_sender.h>

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);

    QTextCodec::setCodecForTr      (QTextCodec::codecForName("UTF-8"));
    QTextCodec::setCodecForCStrings(QTextCodec::codecForName("UTF-8"));
    //QTextCodec::setCodecForLocale  (QTextCodec::codecForName("UTF-8"));

    QByteArray hatml = "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">"
                       "<html>"
"                       <head>"
 "                      <link href=\"css/adak.css\" rel=\"stylesheet\" type=\"text/css\"></link>"
    "                   <script type=\"text/javascript\" src=\"js/adak.js\"></script>"
  "                    <meta http-equiv=\"CONTENT-TYPE\" content=\"text/html; charset=utf-8\">"
     "                  <title>Anasayfa</title>"
      "                 </head>"
       "                <body>"
        "               <table style=\"text-align: left; background-color: rgb(0, 102, 0); width:100%; height: 100%; margin:0;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">"
         "                <tbody>"
          "                 <tr style=\"font-weight: bold;\">"
           "                  <td style=\"vertical-align: top; background-color: rgb(0, 102, 0); width: 784px; height: 103px;\">"
            "                   <big style=\"font-family: Lucida Bright;\">"
             "                  <big>"
              "                         <span style=\"color: white; padding-top:25px;\">Adak Teknoloji</span>"
               "                </big>"
                "               </big>"
                 "            <br>"
                  "           <br>"
                   "          <br>"
                    "         <small>"
                     "          <br>"
                      "         <div class=anamenu>"
                       "         <a href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('anasayfa.html')\">Anasayfa</a> "
                        "        <a style=\"margin-left:30px;\" href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('belgeler.html')\">Belgeler</a>  "
                         "       <a style=\"margin-left:30px;\" href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('bize_ulasin.html')\">Bize Ulaşın</a> "
                          "     <div>"
"                               </span>"
 "                            </small>"
  "                          </span>"
   "                         </td>"
    "                       </tr>"
     "                    </tbody>"
      "                 </table>"
       "                </body>"
       "                       <head>"
        "                      <link href=\"css/adak.css\" rel=\"stylesheet\" type=\"text/css\"></link>"
           "                   <script type=\"text/javascript\" src=\"js/adak.js\"></script>"
         "                    <meta http-equiv=\"CONTENT-TYPE\" content=\"text/html; charset=utf-8\">"
            "                  <title>Anasayfa</title>"
             "                 </head>"
              "                <body>"
               "               <table style=\"text-align: left; background-color: rgb(0, 102, 0); width:100%; height: 100%; margin:0;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">"
                "                <tbody>"
                 "                 <tr style=\"font-weight: bold;\">"
                  "                  <td style=\"vertical-align: top; background-color: rgb(0, 102, 0); width: 784px; height: 103px;\">"
                   "                   <big style=\"font-family: Lucida Bright;\">"
                    "                  <big>"
                     "                         <span style=\"color: white; padding-top:25px;\">Adak Teknoloji</span>"
                      "                </big>"
                       "               </big>"
                        "            <br>"
                         "           <br>"
                          "          <br>"
                           "         <small>"
                            "          <br>"
                             "         <div class=anamenu>"
                              "         <a href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('anasayfa.html')\">Anasayfa</a> "
                               "        <a style=\"margin-left:30px;\" href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('belgeler.html')\">Belgeler</a>  "
                                "       <a style=\"margin-left:30px;\" href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('bize_ulasin.html')\">Bize Ulan</a> "
                                 "     <div>"
       "                               </span>"
        "                            </small>"
         "                          </span>"
          "                         </td>"
           "                       </tr>"
            "                    </tbody>"
             "                 </table>"
              "                </body>"
              "                       <head>"
               "                      <link href=\"css/adak.css\" rel=\"stylesheet\" type=\"text/css\"></link>"
                  "                   <script type=\"text/javascript\" src=\"js/adak.js\"></script>"
                "                    <meta http-equiv=\"CONTENT-TYPE\" content=\"text/html; charset=utf-8\">"
                   "                  <title>Anasayfa</title>"
                    "                 </head>"
                     "                <body>"
                      "               <table style=\"text-align: left; background-color: rgb(0, 102, 0); width:100%; height: 100%; margin:0;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">"
                       "                <tbody>"
                        "                 <tr style=\"font-weight: bold;\">"
                         "                  <td style=\"vertical-align: top; background-color: rgb(0, 102, 0); width: 784px; height: 103px;\">"
                          "                   <big style=\"font-family: Lucida Bright;\">"
                           "                  <big>"
                            "                         <span style=\"color: white; padding-top:25px;\">Adak Teknoloji</span>"
                             "                </big>"
                              "               </big>"
                               "            <br>"
                                "           <br>"
                                 "          <br>"
                                  "         <small>"
                                   "          <br>"
                                    "         <div class=anamenu>"
                                     "         <a href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('anasayfa.html')\">Anasayfa</a> "
                                      "        <a style=\"margin-left:30px;\" href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('belgeler.html')\">Belgeler</a>  "
                                       "       <a style=\"margin-left:30px;\" href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('bize_ulasin.html')\">Bize Ulan</a> "
                                        "     <div>"
              "                               </span>"
               "                            </small>"
                "                          </span>"
                 "                         </td>"
                  "                       </tr>"
                   "                    </tbody>"
                    "                 </table>"
                     "                </body>"
                     "                       <head>"
                      "                      <link href=\"css/adak.css\" rel=\"stylesheet\" type=\"text/css\"></link>"
                         "                   <script type=\"text/javascript\" src=\"js/adak.js\"></script>"
                       "                    <meta http-equiv=\"CONTENT-TYPE\" content=\"text/html; charset=utf-8\">"
                          "                  <title>Anasayfa</title>"
                           "                 </head>"
                            "                <body>"
                             "               <table style=\"text-align: left; background-color: rgb(0, 102, 0); width:100%; height: 100%; margin:0;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">"
                              "                <tbody>"
                               "                 <tr style=\"font-weight: bold;\">"
                                "                  <td style=\"vertical-align: top; background-color: rgb(0, 102, 0); width: 784px; height: 103px;\">"
                                 "                   <big style=\"font-family: Lucida Bright;\">"
                                  "                  <big>"
                                   "                         <span style=\"color: white; padding-top:25px;\">Adak Teknoloji</span>"
                                    "                </big>"
                                     "               </big>"
                                      "            <br>"
                                       "           <br>"
                                        "          <br>"
                                         "         <small>"
                                          "          <br>"
                                           "         <div class=anamenu>"
                                            "         <a href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('anasayfa.html')\">Anasayfa</a> "
                                             "        <a style=\"margin-left:30px;\" href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('belgeler.html')\">Belgeler</a>  "
                                              "       <a style=\"margin-left:30px;\" href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('bize_ulasin.html')\">Bize Ulan</a> "
                                               "     <div>"
                     "                               </span>"
                      "                            </small>"
                       "                          </span>"
                        "                         </td>"
                         "                       </tr>"
                          "                    </tbody>"
                           "                 </table>"
                            "                </body>"
                            "                       <head>"
                             "                      <link href=\"css/adak.css\" rel=\"stylesheet\" type=\"text/css\"></link>"
                                "                   <script type=\"text/javascript\" src=\"js/adak.js\"></script>"
                              "                    <meta http-equiv=\"CONTENT-TYPE\" content=\"text/html; charset=utf-8\">"
                                 "                  <title>Anasayfa</title>"
                                  "                 </head>"
                                   "                <body>"
                                    "               <table style=\"text-align: left; background-color: rgb(0, 102, 0); width:100%; height: 100%; margin:0;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">"
                                     "                <tbody>"
                                      "                 <tr style=\"font-weight: bold;\">"
                                       "                  <td style=\"vertical-align: top; background-color: rgb(0, 102, 0); width: 784px; height: 103px;\">"
                                        "                   <big style=\"font-family: Lucida Bright;\">"
                                         "                  <big>"
                                          "                         <span style=\"color: white; padding-top:25px;\">Adak Teknoloji</span>"
                                           "                </big>"
                                            "               </big>"
                                             "            <br>"
                                              "           <br>"
                                               "          <br>"
                                                "         <small>"
                                                 "          <br>"
                                                  "         <div class=anamenu>"
                                                   "         <a href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('anasayfa.html')\">Anasayfa</a> "
                                                    "        <a style=\"margin-left:30px;\" href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('belgeler.html')\">Belgeler</a>  "
                                                     "       <a style=\"margin-left:30px;\" href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('bize_ulasin.html')\">Bize Ulan</a> "
                                                      "     <div>"
                            "                               </span>"
                             "                            </small>"
                              "                          </span>"
                               "                         </td>"
                                "                       </tr>"
                                 "                    </tbody>"
                                  "                 </table>"
                                   "                </body>"
                                   "                       <head>"
                                    "                      <link href=\"css/adak.css\" rel=\"stylesheet\" type=\"text/css\"></link>"
                                       "                   <script type=\"text/javascript\" src=\"js/adak.js\"></script>"
                                     "                    <meta http-equiv=\"CONTENT-TYPE\" content=\"text/html; charset=utf-8\">"
                                        "                  <title>Anasayfa</title>"
                                         "                 </head>"
                                          "                <body>"
                                           "               <table style=\"text-align: left; background-color: rgb(0, 102, 0); width:100%; height: 100%; margin:0;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">"
                                            "                <tbody>"
                                             "                 <tr style=\"font-weight: bold;\">"
                                              "                  <td style=\"vertical-align: top; background-color: rgb(0, 102, 0); width: 784px; height: 103px;\">"
                                               "                   <big style=\"font-family: Lucida Bright;\">"
                                                "                  <big>"
                                                 "                         <span style=\"color: white; padding-top:25px;\">Adak Teknoloji</span>"
                                                  "                </big>"
                                                   "               </big>"
                                                    "            <br>"
                                                     "           <br>"
                                                      "          <br>"
                                                       "         <small>"
                                                        "          <br>"
                                                         "         <div class=anamenu>"
                                                          "         <a href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('anasayfa.html')\">Anasayfa</a> "
                                                           "        <a style=\"margin-left:30px;\" href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('belgeler.html')\">Belgeler</a>  "
                                                            "       <a style=\"margin-left:30px;\" href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('bize_ulasin.html')\">Bize Ulan</a> "
                                                             "     <div>"
                                   "                               </span>"
                                    "                            </small>"
                                     "                          </span>"
                                      "                         </td>"
                                       "                       </tr>"
                                        "                    </tbody>"
                                         "                 </table>"
                                          "                </body>"
                                          "                       <head>"
                                           "                      <link href=\"css/adak.css\" rel=\"stylesheet\" type=\"text/css\"></link>"
                                              "                   <script type=\"text/javascript\" src=\"js/adak.js\"></script>"
                                            "                    <meta http-equiv=\"CONTENT-TYPE\" content=\"text/html; charset=utf-8\">"
                                               "                  <title>Anasayfa</title>"
                                                "                 </head>"
                                                 "                <body>"
                                                  "               <table style=\"text-align: left; background-color: rgb(0, 102, 0); width:100%; height: 100%; margin:0;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">"
                                                   "                <tbody>"
                                                    "                 <tr style=\"font-weight: bold;\">"
                                                     "                  <td style=\"vertical-align: top; background-color: rgb(0, 102, 0); width: 784px; height: 103px;\">"
                                                      "                   <big style=\"font-family: Lucida Bright;\">"
                                                       "                  <big>"
                                                        "                         <span style=\"color: white; padding-top:25px;\">Adak Teknoloji</span>"
                                                         "                </big>"
                                                          "               </big>"
                                                           "            <br>"
                                                            "           <br>"
                                                             "          <br>"
                                                              "         <small>"
                                                               "          <br>"
                                                                "         <div class=anamenu>"
                                                                 "         <a href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('anasayfa.html')\">Anasayfa</a> "
                                                                  "        <a style=\"margin-left:30px;\" href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('belgeler.html')\">Belgeler</a>  "
                                                                   "       <a style=\"margin-left:30px;\" href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('bize_ulasin.html')\">Bize Ulan</a> "
                                                                    "     <div>"
                                          "                               </span>"
                                           "                            </small>"
                                            "                          </span>"
                                             "                         </td>"
                                              "                       </tr>"
                                               "                    </tbody>"
                                                "                 </table>"
                                                 "                </body>"
                                                 "                       <head>"
                                                  "                      <link href=\"css/adak.css\" rel=\"stylesheet\" type=\"text/css\"></link>"
                                                     "                   <script type=\"text/javascript\" src=\"js/adak.js\"></script>"
                                                   "                    <meta http-equiv=\"CONTENT-TYPE\" content=\"text/html; charset=utf-8\">"
                                                      "                  <title>Anasayfa</title>"
                                                       "                 </head>"
                                                        "                <body>"
                                                         "               <table style=\"text-align: left; background-color: rgb(0, 102, 0); width:100%; height: 100%; margin:0;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">"
                                                          "                <tbody>"
                                                           "                 <tr style=\"font-weight: bold;\">"
                                                            "                  <td style=\"vertical-align: top; background-color: rgb(0, 102, 0); width: 784px; height: 103px;\">"
                                                             "                   <big style=\"font-family: Lucida Bright;\">"
                                                              "                  <big>"
                                                               "                         <span style=\"color: white; padding-top:25px;\">Adak Teknoloji</span>"
                                                                "                </big>"
                                                                 "               </big>"
                                                                  "            <br>"
                                                                   "           <br>"
                                                                    "          <br>"
                                                                     "         <small>"
                                                                      "          <br>"
                                                                       "         <div class=anamenu>"
                                                                        "         <a href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('anasayfa.html')\">Anasayfa</a> "
                                                                         "        <a style=\"margin-left:30px;\" href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('belgeler.html')\">Belgeler</a>  "
                                                                          "       <a style=\"margin-left:30px;\" href=\"javascript:void(0);\" onclick=\"SAYFAYI_DEGISTIR('bize_ulasin.html')\">Bize Ulan</a> "
                                                                           "     <div>"
                                                 "                               </span>"
                                                  "                            </small>"
                                                   "                          </span>"
                                                    "                         </td>"
                                                     "                       </tr>"
                                                      "                    </tbody>"
                                                       "                 </table>"
                                                        "                </body>"
        "               </html>";
    QString l = QString::fromLocal8Bit("üppğğğğşşşşıı");
    QString text = "üppğğğğşşşşıı";

    QTextCodec * codec = QTextCodec::codecForName("ISO 8859-9");
    QString html = codec->toUnicode(hatml);


    QByteArray username = QVariant("cerdeneme").toByteArray().toBase64();
    QByteArray password = QVariant("1.cerdeneme").toByteArray().toBase64();



    qDebug(html.toUtf8().data());

    ADAK_EMAIL_SENDER("cerdeneme@hotmail.com", "cavit.vural@adak.com.tr", "cavit.vural@adak.com.tr", "a",NULL);
    //SEND_MAIL("cerdeneme@hotmail.com","asd" ,"cavit.vural@adak.com.tr , cerdenemee@gmail.com", "asd123as", html);

    a.exec();

    return 0;
}


