rm -rf ADAK_STD/MINGW
rm -rf BELGE_KERNEL/MINGW
rm -rf DESIGNER/MINGW
rm -rf EMAIL/MINGW
rm -rf GRUP_KERNEL/MINGW
rm -rf KERNEL/MINGW
rm -rf LOGIN/MINGW
rm -rf MINGW
rm -rf MENU_KERNEL/MINGW
rm -rf ODS_IO/MINGW
rm -rf QAdakDate/MINGW
rm -rf QCommaEdit/MINGW
rm -rf QLimitedTextEdit/MINGW
rm -rf QSearchEdit/MINGW
rm -rf REPORT_KERNEL/MINGW
rm -rf SMS/MINGW
rm -rf SQL/MINGW
rm -rf TASARIMCI/MINGW
rm -rf UPDATE_DB/MINGW
rm -rf UTILS/MINGW
rm -rf YONETIM/MINGW
