rm -rf ADAK_STD/MACOSX ADAK_STD/Makefile
rm -rf BELGE_KERNEL/MACOSX BELGE_KERNEL/Makefile
rm -rf DESIGNER/MACOSX DESIGNER/Makefile
rm -rf EMAIL/MACOSX EMAIL/Makefile
rm -rf GRUP_KERNEL/MACOSX GRUP_KERNEL/Makefile
rm -rf KERNEL/MACOSX KERNEL/Makefile
rm -rf LOGIN/MACOSX LOGIN/Makefile
rm -rf MACOSX Makefile
rm -rf MENU_KERNEL/MACOSX MENU_KERNEL/Makefile
rm -rf ODS_IO/MACOSX ODS_IO/Makefile
rm -rf QAdakDate/MACOSX QAdakDate/Makefile
rm -rf QCommaEdit/MACOSX QCommaEdit/Makefile
rm -rf QLimitedTextEdit/MACOSX QLimitedTextEdit/Makefile
rm -rf QSearchEdit/MACOSX QSearchEdit/Makefile
rm -rf REPORT_KERNEL/MACOSX REPORT_KERNEL/Makefile
rm -rf SMS/MACOSX SMS/Makefile
rm -rf SQL/MACOSX SQL/Makefile
rm -rf TASARIMCI/MACOSX TASARIMCI/Makefile
rm -rf UPDATE_DB/MACOSX UPDATE_DB/Makefile
rm -rf UTILS/MACOSX UTILS/Makefile
rm -rf YONETIM/MACOSX YONETIM/Makefile
