#ifndef DOT_MATRIX_SABITLER_H
#define DOT_MATRIX_SABITLER_H

class QString;

QString GET_IBM_NORMAL();
QString GET_IBM_NLQ();
QString GET_IBM_RESET_MODE();
QString GET_IBM_LARGE_MODE();
QString GET_IBM_CONDENSEN_MODE();
QString GET_EPSON_NORMAL();
QString GET_EPSON_NLQ();
QString GET_EPSON_NORMAL_MODE();
QString GET_EPSON_LARGE_MODE();
QString GET_EPSON_CONDENSEN_MODE();


#endif // DOT_MATRIX_SABITLER_H
