#ifndef DOVIZLER_H
#define DOVIZLER_H

/***************************************************


        Kayitlar eklenirken alfabetik siraya dikkat edilmeli


**************************************************/

const char * dovizler[][2] = {
    {"AFN","Afghani"},
    {"AUD","Avustralya Doları"},
    {"AOA","Kuanza"},
    {"ALL","Lek"},
    {"AED","Birleşik Arap Emirlikleri Dirhemi"},
    {"AMD","Ermeni Dramı"},
    {"ARS","Pezo"},
    {"AZN","Azerbaycan Manatı"},
    {"BGL","Bulgar Levası"},
    {"BSD","Bahama Doları"},
    {"BHD","Bahreyn Dinarı"},
    {"BDT","Taka"},
    {"BBD","Barbados Doları"},
    {"BYR","Beyaz Rusya Rublesi"},
    {"BZD","Belize Doları"},
    {"BTM","Ngultrum"},
    {"BOB","Boliviano"},
    {"BAM","Konvertibıl Mark"},
    {"BWP","Pula"},
    {"BRL","Real"},
    {"BND","Bruney Doları"},
    {"BGN","Leva"},
    {"BIF","Burundi Franc"},
    {"CAD","Kanada Doları"},
    {"CZK","Çek Korunası"},
    {"CNY","Yuan"},
    {"CVE","Escudo cabo-verdiano"},
    {"CNF","Gine Frankı"},
    {"COP","Kolombiya Pezosu "},
    {"CDF","Kongo Frangı"},
    {"CRC","Colón"},
    {"CUC","Küba Pezosu"},
    {"CSD","Sırp Dinarı"},
    {"CLP","Şili Pezosu"},
    {"DKK","Danimarka Kronu"},
    {"DOP","Dominik Pezosu"},
    {"DZD","Cezayir Dinari"},
    {"DJF","Cibuti Frangı"},
    {"EUR","Euro"},
    {"ERN","Nakfa"},
    {"EEK","Estonya Kronu"},
    {"EGP","Egyptian Pound"},
    {"ETB","Birr"},
    {"HKD","Hong Kong Doları"},
    {"HNL","Lempira"},
    {"HRK","Kuna"},
    {"HTG","Gourde"},
    {"GBP","İngiliz Sterlini"},
    {"ILS","İsrail Şekeli"},
    {"IRR","İran Riyali"},
    {"JOD","Ürdün Dinarı"},
    {"JPY","Japon Yeni"},
    {"KWD","Kuveyt Dinarı"},
    {"NOK","Norveç Kronu"},
    {"SAR","Suudi Arabistan Riyali"},
    {"SEK","İsveç Kronu"},
    {"SYP","Suriye Lirası"},
    {"USD","Amerikan Doları"},
    {"XCD","Doğu Karayip Doları"},
    {"TL" ,"Türk Lirası"},
    {"XOF","CFA Frangı"},
    {"IDR","Endonezya Rupisi"},
    {"FJD","Fiji Doları"},
    {"PHP","Filipinler Pezosu"},
    {"GMD","Dalasi"},
    {"GHS","Ghanaian Cedi"},
    {"GYD","Guyanese Doları"},
    {"GTQ","Quetzal"},
    {"ZAR","Rand"},
    {"KRW","Güney Kore Won"},
    {"GEL","Lari"},
    {"INR","Hint Rupisi"},
    {"IQD","Irak Dinarı"},
    {"CHF","İsviçre frangı"},
    {"ISK","İzlanda Kronası"},
    {"JMD","Jamaican Doları"},
    {"KHR","Riel"},
    {"QAR","Katar Riyali"},
    {"KZT","Tenge"},
    {"KES","Kenyan Shilling"},
    {"KGS","Kırgızistan Somu"},
    {"KMF","Komor Frankı"},
    {"KPW","Kuzey Kore Won"},
    {"LAK","Kip"},
    {"LSL","Loti"},
    {"LVL","Letonya Latsı"},
    {"LRD","Liberya Doları"},
    {"LYD","Libya Dinarı"},
    {"LTL","Litvanya Litası"},
    {"LBP","Lübnan Lirası"},
    {"HUF","Forint"},
    {"MAD","Fas Dirhemi"},
    {"MGA","Madagaskar Ariarisi"},
    {"MKD","Denar"},
    {"MWK","Kwacha"},
    {"MVR","Rufiyaa"},
    {"MYR","Ringgit"},
    {"MXN","Meksika Pezosu"},
    {"MNT","Tugrug"},
    {"MDL","Moldova Leyi"},
    {"MRO","Ouguiya"},
    {"MUR","Mauritius Rupisi"},
    {"MZN","Mozambican Metical "},
    {"MMK","Kyat"},
    {"NAD","Namibya Doları"},
    {"NPR","Rupee"},
    {"NIO","Kordoba"},
    {"NGN","Naira"},
    {"NZD","Yeni Zelanda Doları"},
    {"UZS","Özbekistan Somu"},
    {"PKR","Rupi"},
    {"PGK","Papua Yeni Gine Kinası"},
    {"PYG","Paraguay Guaranisi"},
    {"PEN","Nuevo Sol"},
    {"PLN","Polonya Zlotisi"},
    {"PRB","Transnistrian Rublesi"},
    {"RON","Rumen Leyi"},
    {"RWF","Ruanda Frankı"},
    {"RUB","Rus Rublesi"},
    {"WST","Tala"},
    {"STD","Dobra"},
    {"SCR","Şeyşeller Rupisi"},
    {"SLL","Leone"},
    {"SGD","Singapur Doları"},
    {"SBD","Solomon Adaları Doları "},
    {"SOS","Somali Şilini"},
    {"SLSH","Somaliland Shilling "},
    {"LKR","Sri Lanka Rupisi"},
    {"SDG","Sudan Sterlini"},
    {"SRD","Surinam Doları"},
    {"SZL","Lilangeni"},
    {"TJS","Somoni"},
    {"TZS","Tanzanya Şilini"},
    {"THB","Thay Bahtı"},
    {"TWD","Yeni Tayvan Doları"},
    {"TOP","Paanga"},
    {"TTD","Trinidad ve Tobago Doları"},
    {"TND","Tunus Dinarı"},
    {"TMT","Türkmenistan Manatı"},
    {"UGX","Uganda Şilini"},
    {"UAH","Grivna"},
    {"OMR","Umman Riyali"},
    {"UYU","Uruguay Pesosu"},
    {"VUV","Vanuatu Vatu"},
    {"VEF","Dinç Bolívarı"},
    {"VND","Đồng"},
    {"YER","Yemen Riyali"},
    {"ZMK","Zambian Kwacha"},
    {"ZWD","Zimbabve Doları"},
    {"",""}
};


#endif // DOVIZLER_H
