#ifndef ILLER_H
#define ILLER_H

/***************************************************


        Kayitlar eklenirken alfabetik siraya dikkat edilmeli


**************************************************/

const char * iller[][5]= {
    {"Türkiye", "Adana",         "322",  "",    "01"},
    {"Türkiye", "Adıyaman",      "416",  "",    "02"},
    {"Türkiye", "Afyon",         "272",  "",    "03"},
    {"Türkiye", "Ağrı",          "472",  "",    "04"},
    {"Türkiye", "Aksaray",       "382",  "",    "68"},
    {"Türkiye", "Amasya",        "358",  "",    "05"},
    {"Türkiye", "Ankara",        "312",  "",    "06"},
    {"Türkiye", "Antalya",       "242",  "",    "07"},
    {"Türkiye", "Ardahan",       "478",  "",    "75"},
    {"Türkiye", "Artvin",        "466",  "",    "08"},
    {"Türkiye", "Aydın",         "256",  "",    "09"},
    {"Türkiye", "Balıkesir",     "266",  "",    "10"},
    {"Türkiye", "Bartın",        "378",  "",    "74"},
    {"Türkiye", "Batman",        "488",  "",    "72"},
    {"Türkiye", "Bayburt",       "458",  "",    "69"},
    {"Türkiye", "Bilecik",       "228",  "",    "11"},
    {"Türkiye", "Bingöl",        "426",  "",    "12"},
    {"Türkiye", "Bitlis",        "434",  "",    "13"},
    {"Türkiye", "Bolu",          "374",  "",    "14"},
    {"Türkiye", "Burdur",        "248",  "",    "15"},
    {"Türkiye", "Bursa",         "224",  "",    "16"},
    {"Türkiye", "Çanakkale",     "286",  "",    "17"},
    {"Türkiye", "Çankırı",       "376",  "",    "18"},
    {"Türkiye", "Çorum",         "364",  "",    "19"},
    {"Türkiye", "Denizli",       "258",  "",    "20"},
    {"Türkiye", "Diyarbakır",    "412",  "",    "21"},
    {"Türkiye", "Düzce",         "380",  "",    "81"},
    {"Türkiye", "Edirne",        "284",  "",    "22"},
    {"Türkiye", "Elazığ",        "424",  "",    "23"},
    {"Türkiye", "Erzincan",      "446",  "",    "24"},
    {"Türkiye", "Erzurum",       "442",  "",    "25"},
    {"Türkiye", "Eskişehir",     "222",  "",    "26"},
    {"Türkiye", "Gaziantep",     "342",  "",    "27"},
    {"Türkiye", "Giresun",       "454",  "",    "28"},
    {"Türkiye", "Gümüşhane",     "456",  "",    "29"},
    {"Türkiye", "Hakkari",       "438",  "",    "30"},
    {"Türkiye", "Hatay",         "326",  "",    "31"},
    {"Türkiye", "Iğdır",         "476",  "",    "76"},
    {"Türkiye", "Isparta",       "246",  "",    "32"},
    {"Türkiye", "Mersin",        "324",  "",    "33"},
    {"Türkiye", "İstanbul",      "212", "216",  "34"},
    {"Türkiye", "İzmir",         "232",  "",    "35"},
    {"Türkiye", "Karabük",       "370",  "",    "78"},
    {"Türkiye", "Karaman",       "338",  "",    "70"},
    {"Türkiye", "Kars",          "474",  "",    "36"},
    {"Türkiye", "Kastamonu",     "366",  "",    "37"},
    {"Türkiye", "Kayseri",       "352",  "",    "38"},
    {"Türkiye", "Kırıkkale",     "318",  "",    "71"},
    {"Türkiye", "Kırklareli",    "288",  "",    "39"},
    {"Türkiye", "Kırşehir",      "386",  "",    "40"},
    {"Türkiye", "Kilis",         "348",  "",    "79"},
    {"Türkiye", "Kahramanmaraş", "344",  "",    "46"},
    {"Türkiye", "Kocaeli",       "262",  "",    "41"},
    {"Türkiye", "Konya",         "332",  "",    "42"},
    {"Türkiye", "Kütahya",       "274",  "",    "43"},
    {"Türkiye", "Malatya",       "422",  "",    "44"},
    {"Türkiye", "Manisa",        "236",  "",    "45"},
    {"Türkiye", "Mardin",        "482",  "",    "47"},
    {"Türkiye", "Muğla",         "252",  "",    "48"},
    {"Türkiye", "Muş",           "436",  "",    "49"},
    {"Türkiye", "Nevşehir",      "384",  "",    "50"},
    {"Türkiye", "Niğde",         "388",  "",    "51"},
    {"Türkiye", "Ordu",          "452",  "",    "52"},
    {"Türkiye", "Osmaniye",      "328",  "",    "80"},
    {"Türkiye", "Rize",          "464",  "",    "53"},
    {"Türkiye", "Sakarya",       "264",  "",    "54"},
    {"Türkiye", "Samsun",        "362",  "",    "55"},
    {"Türkiye", "Siirt",         "484",  "",    "56"},
    {"Türkiye", "Sinop",         "368",  "",    "57"},
    {"Türkiye", "Sivas",         "346",  "",    "58"},
    {"Türkiye", "Şanlıurfa",     "414",  "",    "63"},
    {"Türkiye", "Şırnak",        "486",  "",    "73"},
    {"Türkiye", "Tekirdağ",      "282",  "",    "59"},
    {"Türkiye", "Tokat",         "356",  "",    "60"},
    {"Türkiye", "Trabzon",       "462",  "",    "61"},
    {"Türkiye", "Tunceli",       "428",  "",    "62"},
    {"Türkiye", "Uşak",          "276",  "",    "64"},
    {"Türkiye", "Van",           "432",  "",    "65"},
    {"Türkiye", "Yalova",        "226",  "",    "77"},
    {"Türkiye", "Yozgat",        "354",  "",    "66"},
    {"Türkiye", "Zonguldak",     "372",  "",    "67"},
    {"","","","",""                                }};

#endif // ILLER_H
