#ifndef MESLEKLER_H
#define MESLEKLER_H

/***************************************************


        Kayitlar eklenirken alfabetik siraya dikkat edilmeli


**************************************************/

const char * meslekler[][1] = {
    {"Acil tıp Teknisyeni"},
    {"Ağaç İşleri Endüstri Mühendisi"},
    {"Akademisyen"},
    {"Anestezi Teknikeri"},
    {"Ar Ge Mühendisi"},
    {"Arıcılık Teknikeri"},
    {"Arkeolog"},
    {"Arşivci"},
    {"Asansör Kurucusu ve Bakımcısı"},
    {"Aşçı"},
    {"Av ve Yaban Hayatı Teknikeri"},
    {"Avrupa birliği İlişkileri Elemanı"},
    {"Avukat"},
    {"Bağcılık Teknikeri"},
    {"Bankacı"},
    {"Bilgisayar Ağ İşletmeni"},
    {"Bilgisayar Öğretmeni"},
    {"Bilgi İşlemci"},
    {"Bilgisayarlı Numerik Kontrolcü"},
    {"Bilgisayar Mühendisi"},
    {"Bilgisayar Programcısı"},
    {"Biyomedikalcı"},
    {"Biyalog"},
    {"Bina tesis Yöneticisi"},
    {"Bütçe Uzmanı"},
    {"Çevre Mühendisi"},
    {"Çevre Teknikeri"},
    {"Çiçekçi"},
    {"Çiftçi"},
    {"Çocuk Geliştirme Uzmanı"},
    {"Coğrafyacı"},
    {"Çilingir"},
    {"Dansçı"},
    {"Danışman"},
    {"Dekorasyoncu"},
    {"deniz ve Liman İşletme Meslek elemanı"},
    {"Denizcilik İşletmeleri Yöneticisi"},
    {"Dericilik Teknikeri"},
    {"Desinatör"},
    {"Diş Teknik Sekreteri"},
    {"Diş Hekimi"},
    {"Dış Ticaret Uzmanı"},
    {"Dış Protez Teknisyeni"},
    {"Diyetisyen"},
    {"Doğalgaz Tesisat Teknisyeni"},
    {"Doğalgaz Isıtma ve Sıhhı Tesisat Teknisyeni"},
    {"Doktor"},
    {"Ebe"},
    {"Eczane Teknisyeni"},
    {"Eczacı"},
    {"Eğitim Uzmanı"},
    {"Ekonomist"},
    {"Elektrik Elektronik Mühendisi"},
    {"Elektronik Teknisyeni"},
    {"Elek.Haberleşme Mühendisi"},
    {"Elektrik Teknikeri"},
    {"Elektrik Teknisyeni"},
    {"Elektronik Teknikeri"},
    {"Elektrik Mühendisi"},
    {"Elektronik Mühendisi"},
    {"Emlakçı"},
    {"Endüstri Ürünleri Tasarımcısı"},
    {"Endüstri Mühendisi"},
    {"Endüstriyel Elektornik Teknikeri"},
    {"Esnaf"},
    {"Endüstriyel Yazılım Mühendisi"},
    {"Felsefeci"},
    {"Film Yapımcısı"},
    {"Finans Uzmanı"},
    {"Fırıncı"},
    {"Fizik Mühendisi"},
    {"Fizyoterepist"},
    {"Fizikçi"},
    {"Fotoğrafcı"},
    {"Fuar Organizasyoncusu"},
    {"Gayrimenkul Danuşmanı"},
    {"Gayrimenkul Değerleme Uzmanı"},
    {"Gazeteci"},
    {"Gemi Mühendisi"},
    {"Gemi Kaptanı"},
    {"Gıda Teknisyeni"},
    {"Gıda Mühendisi"},
    {"Gıda Teknikeri"},
    {"Grafiker"},
    {"Grafik Tasarımcısı"},
    {"Gümrük Müşaviri"},
    {"Güzellik Uzmanı"},
    {"Halklar İlişkiler"},
    {"Harita Mühendisi"},
    {"Hayvan Sağlığı Teknikeri"},
    {"Hemşire"},
    {"Heykeltraş"},
    {"Hidrojeoloji Mühendisi"},
    {"Hukukçu"},
    {"Hurdacı"},
    {"İç Mimar"},
    {"İkl.Soğutma Teknikeri"},
    {"İktisatçı"},
    {"İnşaat Mühendisi"},
    {"İnsan Kaynakları Uzmanı"},
    {"İnşaat Teknikeri"},
    {"İnşaat Teknisyeni"},
    {"İş Analistleri"},
    {"İşletme Mühendisi"},
    {"İşletmeci"},
    {"İstatikçi"},
    {"İtfaiyecilik ve Yangın Güvenliği Teknikeri"},
    {"İş Sağlığı ve Güvenliği Uzmanı"},
    {"Jeoloji Mühendisi"},
    {"Jeofizik Mühendisi"},
    {"Kabin Memuru"},
    {"Kalite Uzmanı"},
    {"Kameraman"},
    {"Kasiyer"},
    {"Kaynakçı"},
    {"Kimyager"},
    {"Kimya mühendisi"},
    {"Kuaför"},
    {"Kule Vinç Operatörü"},
    {"Kurye"},
    {"Kütüphaneci"},
    {"Kuyumcu"},
    {"Laborant"},
    {"Laboratuar Teknisyeni"},
    {"Lojistik Uzmanı"},
    {"Maden Mühendisi"},
    {"Makine Teknikeri"},
    {"Makina Mühendisi"},
    {"Mali Müşavir"},
    {"Maliyeci"},
    {"Mantar Teknikeri"},
    {"Manken"},
    {"Marka Uzmanı"},
    {"Matematik Mühendisi"},
    {"Matematikçi"},
    {"Matbaacı"},
    {"Mekatronik Mühendisi"},
    {"Mekatronik Teknikeri"},
    {"Memur"},
    {"Meteoroloji Mühendisi"},
    {"Metalurji Malzeme Teknikeri"},
    {"Metalurji Mühendisi"},
    {"Mimar"},
    {"Muhasebeci"},
    {"Müşteri Temsilcisi"},
    {"Odyometristler"},
    {"Ofis Asistanı"},
    {"Öğrenci"},
    {"Öğretmen"},
    {"Optisyen"},
    {"Organik Tarım Teknikeri"},
    {"Orman Mühendisi"},
    {"Orman Endüstri Mühendisi"},
    {"Otomotivci"},
    {"Özel Güvenlikçi"},
    {"Patent Müşaviri"},
    {"Patoloji Laboratuar Teknikeri"},
    {"Petrol Mühendisi"},
    {"Peyzaj Teknikeri"},
    {"Peyzaj Mimarı"},
    {"Pilot"},
    {"Polis"},
    {"Psikolog"},
    {"Psikolojik Danışman"},
    {"Psikiyatrist"},
    {"Radyo ve Televizyon Spikeri"},
    {"Televizyoncu"},
    {"Radyocu"},
    {"Radyoloji Teknisyeni"},
    {"Reklamcı"},
    {"Ressam"},
    {"Sağlık Eğitimcisi"},
    {"Sağlık Memuru"},
    {"Sanatçı"},
    {"Santral Operatörü"},
    {"Sanat Tarihçisi"},
    {"Satış ve Pazarlamacı"},
    {"Satın Alma Sorumlusu"},
    {"Şehir Planlamacısı"},
    {"Sekreter"},
    {"Seramik Teknikeri"},
    {"Sigortacı"},
    {"Sigorta Eksperi"},
    {"Sigorta Brokeri"},
    {"Şöför"},
    {"Sosyal Hizmetler Uzmanı"},
    {"Sosyal Çalışmacı"},
    {"Sosyolog"},
    {"Stilist"},
    {"Su Ürünleri Teknikeri"},
    {"Su Ürünleri Mühendisi"},
    {"Takı Tasarımcıları"},
    {"Tamirci"},
    {"Tarihçi"},
    {"Tattoo Sanatçısı"},
    {"Tekstil Mühendisi"},
    {"Tekstilci"},
    {"Tekstil Tasarım Teknisyeni"},
    {"Teknik Ressam"},
    {"Telekomünikasyoncu"},
    {"Telekomünikasyon Teknikeri"},
    {"Telekomünikasyon Mühendisi"},
    {"Tercüman"},
    {"Tesviyeci"},
    {"Tesisatçı"},
    {"Tıbbi Mümessil"},
    {"Tıbbi Teknolog"},
    {"Tıbbi Sekreter"},
    {"Tiyatro Oyuncusu"},
    {"Topograf"},
    {"Trafik Müşaviri"},
    {"Turizmci"},
    {"Türkolog"},
    {"Uçak Mühendisi"},
    {"Uluslararası İlişkiler"},
    {"Veteriner Hekim"},
    {"Veteriner Sağlık Teknisyeni"},
    {"Webmaster"},
    {"Yalıtım Teknikeri"},
    {"Yapı Öğretmeni"},
    {"Yapı Teknisyeni"},
    {"Yayıncı"},
    {"Yazar"},
    {"Yönetim Bilişim Sistemleri Uzmanı"},
    {"Yönetici Sekreter"},
    {"Yönetici"},
    {"Zabıta"},
    {"Ziraat Mühendisi"},
    {"Ziraat Teknikeri"},
    {""}
};

#endif // MESLEKLER_H
