#ifndef SEKTORLER_H
#define SEKTORLER_H

const char * sektorler[][1] = {
    {"Ağaç-Ahşap"},
    {"Alışveriş"},
    {"Ambalaj Sanayi"},
    {"Bahçe ve Çiçek"},
    {"Basın Yayın Matbaa"},
    {"Bilgisayar-Yazılım"},
    {"Bilim ve Teknoloji"},
    {"Boya-Sanayi"},
    {"Cam ve Ayna"},
    {"Çevre Su ve Arıtma"},
    {"Dekorasyon"},
    {"Denizcilik ve Gemi"},
    {"Deri Sanayi"},
    {"Eğitim"},
    {"Ekonomi Para"},
    {"Elektrik"},
    {"Elektronik"},
    {"Elektronik Sanayi"},
    {"Emlak-Gayrimenkul"},
    {"Endüstriyel"},
    {"Enerji"},
    {"Ev Yaşam"},
    {"Gıda"},
    {"Giyim"},
    {"Güvenlik"},
    {"Güzellik ve Bakım"},
    {"Hayvancılık"},
    {"Hizmet"},
    {"Holdingler"},
    {"Hurda"},
    {"İhracat"},
    {"İnşaat Dekorasyon"},
    {"İnşaat"},
    {"İnternet Hizmetleri"},
    {"Isıtma Soğutma"},
    {"İthalat"},
    {"Jeoloji-Zemin"},
    {"Kağıt Sanayi"},
    {"Kimya Sanayi"},
    {"Kültür Sanayi"},
    {"Lastik Sanayi"},
    {"Lojistik-Nakliye"},
    {"Maden"},
    {"Makina Sanayi"},
    {"Metal Sanayi"},
    {"Mobilya Sanayi"},
    {"Moda-Giyim"},
    {"Muhasebe"},
    {"Mühendislik/Mimarlık"},
    {"Ofis-Kırtasiye"},
    {"Organizasyon"},
    {"Otomotiv Sanayi"},
    {"Oyun-Oyuncak"},
    {"Perakende"},
    {"Plastik"},
    {"Porselen"},
    {"Reklam Tanıtım"},
    {"Sağlık"},
    {"Seramik"},
    {"Spor"},
    {"Takı-Mücevherat"},
    {"Tarım"},
    {"Tekstil"},
    {"Telekominikasyon"},
    {"Temizlik"},
    {"Turizm-Seyahat"},
    {"Yaşam-İnsanlar"},
    {"Sigorta"},
    {""}
};

#endif // SEKTORLER_H
