#ifndef ULKELER_H
#define ULKELER_H

/***************************************************


        Kayitlar eklenirken alfabetik siraya dikkat edilmeli


**************************************************/

const char * ulkeler[][4] = {
    {"Abhazya",                           "",       "" ,"RUB"},
    {"Afganistan",                      "93",     "AF" ,"AFN"},
    {"Almanya",                         "41",     "D" ,"EUR"},
    {"Amerika Birleşik Devletleri",     "1",      "US" ,"USD"},
    {"Andorra",                         "376",    "AD" ,"EUR"},
    {"Angola",                          "244",    "AO" ,"AOA"},
    {"Antigua ve Barbuda",              "1-268",  "AG" ,"XCD"},
    {"Arjantin",                        "54",     "AR" ,"ARS"},
    {"Arnavutluk",                      "355",    "AL" ,"ALL"},
    {"Avustralya",                      "61",     "AU" ,"AUD"},
    {"Avusturya",                       "43",     "AT" ,"EUR"},
    {"Azerbaycan ",                     "994",    "AZ" ,"AZN"},
    {"Bahamalar",                       "1-242",  "BS" ,"BSD"},
    {"Bahreyn",                         "973",    "BH" ,"BHD"},
    {"Bangladeş",                       "880",    "BD" ,"BDT"},
    {"Barbados",                        "1-246",  "BB" ,"BBD"},
    {"Batı Sahra",                      "+212",   "EH" ,"MAD"},
    {"Belarus",                         "375",    "BY" ,"BYR"},
    {"Belçika",                         "32",     "BE" ,"EUR"},
    {"Belize",                          "501",    "BZ" ,"BZD"},
    {"Benin",                           "229",    "BJ" ,"XOF"},
    {"Bhutan",                          "975",    "BL" ,"BTM"},
    {"Birleşik Arap Emirlikleri",       "971",    "AE" ,"AED"},
    {"Bolivya",                         "591",    "BO" ,"BOB"},
    {"Bosna Hersek",                    "387",    "BA" ,"BAM"},
    {"Botsvana",                        "+267",   "BW" ,"BWP"},
    {"Brezilya",                        "55",     "BR" ,"BRL"},
    {"Brunei",                          "673",    "BN" ,"BND"},
    {"Bulgaristan",                     "359",    "BG" ,"BGN"},
    {"Burkina Faso",                    "226",    "BF" ,"XOF"},
    {"Burundi",                         "257",    "Bİ" ,"BIF"},
    {"Cezayir",                         "213",    "DZ" ,"DZD"},
    {"Cibuti Cumhuriyeti",              "253",    "DJ" ,"DJF"},
    {"Çad",                             "235",    "TD" ,"XOF"},
    {"Çek Cumhuriyeti",                 "420",    "CZ" ,"CZK"},
    {"Çin Halk Cumhuriyeti",            "86",     "CN" ,"CNY"},
    {"Dağlık Karabağ Cumhuriyeti",      "374-47", "" ,"AMD"},
    {"Danimarka",                       "45",       "DK" ,"DKK"},
    {"Doğu Timor",                      "670",       "TL" ,"USD"},
    {"Dominik Cumhuriyeti",             "1-809",       "DO" ,"DOP"},
    {"Dominika",                        "+1-767",       "" ,"XCD"},
    {"Ekvador",                         "593",       "EC" ,"USD"},
    {"Ekvator Ginesi",                  "240",       "GQ" ,"XOF"},
    {"El Salvador",                     "503",       "SV" ,"USD"},
    {"Endonezya",                       "62",       "ID" ,"IDR"},
    {"Eritre",                          "291",       "ER" ,"ERN"},
    {"Ermenistan",                      "374",       "AM" ,"AMD"},
    {"Estonya",                         "372",       "EE" ,"EEK"},
    {"Etiyopya",                        "251",       "ET" ,"ETB"},
    {"Fas",                             "212",       "MA" ,"MAD"},
    {"Fiji",                            "679",       "FJ" ,"FJD"},
    {"Fildişi Sahilleri",               "225",       "CI" ,"XOF"},
    {"Filipinler",                      "+63",       "PH" ,"PHP"},
    {"Filistin",                        "970",       "PS" ,"JOD"},
    {"Finlandiya",                      "358",       "FI" ,"EUR"},
    {"Fransa",                          "33",     "F" ,"EUR"},
    {"Gabon",                           "241",       "GA" ,"XOF"},
    {"Gambiya",                         "220",       "GM" ,"GMD"},
    {"Gana",                            "233",       "GH" ,"GHS"},
    {"Gine Bissau",                     "245",       "GW" ,"XOF"},
    {"Gine",                            "224",       "GN" ,"CNF"},
    {"Grenada",                         "1-473",       "GD" ,"XCD"},
    {"Guyana",                          "592",       "GY" ,"GYD"},
    {"Guatemala",                       "502",       "GT" ,"GTQ"},
    {"Güney Afrika Cumhuriyeti",        "+27",       "ZA" ,"ZAR"},
    {"Güney Kore",                      "82",       "KR" ,"KRW"},
    {"Gürcistan",                       "995",       "GE" ,"GEL"},
    {"Haiti",                           "509",       "HT" ,"HTG"},
    {"Hırvatistan",                     "385",       "HR" ,"HRK"},
    {"Hindistan",                       "91",       "IN" ,"INR"},
    {"Hollanda",                        "31",       "NL" ,"EUR"},
    {"Honduras",                        "504",       "HN" ,"HNL"},
    {"Hong Kong",                       "+852",      "HK" ,"HKD"},
    {"Irak",                            "964",       "IQ" ,"IQD"},
    {"İngiltere",                       "44",     "G" ,"GBP"},
    {"İran",                            "98",       "IR" ,"IRR"},
    {"İrlanda",                         "353",       "IE" ,"EUR"},
    {"İspanya",                         "34",       "ES" ,"EUR"},
    {"İsrail",                          "972",       "IL" ,"ILS"},
    {"İsveç",                           "46",       "SE" ,"SEK"},
    {"İsviçre",                         "41",       "CH" ,"CHF"},
    {"İtalya",                          "39",       "IT" ,"EUR"},
    {"İzlanda",                         "354",       "IS" ,"ISK"},
    {"Jamaika",                         "+1-876",       "JM" ,"JMD"},
    {"Japonya",                         "81",       "JP" ,"JPY"},
    {"Kamboçya",                        "855",       "KH" ,"KHR"},
    {"Kamerun",                         "237",       "CM" ,"XOF"},
    {"Kanada",                          "1",       "CA" ,"CAD"},
    {"Karadağ",                         "382",       "YU" ,"EUR"},
    {"Katar",                           "974",       "QA" ,"QAR"},
    {"Kazakistan",                      "7",       "KZ" ,"KZT"},
    {"Kenya",                           "+254",       "KE" ,"KES"},
    {"Kırgızistan",                     "+996",       "KG" ,"KGS"},
    {"Kıbrıs Rum Kesimi",               "357",       "CY" ,"EUR"},
    {"Kiribati",                        "686",       "KI" ,"AUD"},
    {"Kolombiya",                       "+57",       "CO" ,"COP"},
    {"Komorlar",                        "269",       "KM" ,"KMF"},
    {"Kongo",                           "242",       "CG" ,"XOF"},
    {"Kongo Demokratik Cumhuriyeti",    "243",       "CD" ,"CDF"},
    {"Kosova",                          "381",       "KO" ,"EUR"},
    {"Kosta Rika",                      "506",       "CR" ,"CRC"},
    {"Kuveyt",                          "965",       "KW" ,"KWD"},
    {"Kuzey Kıbrıs Türk Cumhuriyeti",   "90-392",       "NCTR" ,"TL"},
    {"Kuzey Kore",                      "850",       "KP" ,"KPW"},
    {"Küba",                            "+53",       "CU" ,"CUC"},
    {"Laos",                            "856",       "LA" ,"LAK"},
    {"Lesotho",                         "266",       "LS" ,"LSL"},
    {"Letonya",                         "371",       "LV" ,"LVL"},
    {"Liberya",                         "231",       "LR" ,"LRD"},
    {"Libya",                           "218",       "LY" ,"LYD"},
    {"Liechtenstein",                   "423",       "LI" ,"CHF"},
    {"Litvanya",                        "370",       "LT" ,"LTL"},
    {"Lübnan",                          "961",       "LB" ,"LBP"},
    {"Lüksemburg",                      "352",       "LU" ,"EUR"},
    {"Macaristan",                      "36",       "HU" ,"HUF"},
    {"Madagaskar",                      "261",       "MG" ,"MGA"},
    {"Makedonya Cumhuriyeti",           "389",       "MK" ,"MKD"},
    {"Malavi",                          "265",       "MW" ,"MWK"},
    {"Maldivler",                       "960",       "MV" ,"MVR"},
    {"Malezya",                         "60",       "MY" ,"MYR"},
    {"Mali",                            "223",       "ML" ,"XOF"},
    {"Malta",                           "356",       "MT" ,"EUR"},
    {"Marshall Adaları",                "692",       "MH" ,"USD"},
    {"Meksika",                         "+52",       "MX" ,"MXN"},
    {"Mısır",                           "+20",       "EG" ,"EGP"},
    {"Mikronezya",                      "691",       "FM" ,"USD"},
    {"Moğolistan",                      "976",       "MN" ,"MNT"},
    {"Moldova",                         "373",       "MD" ,"MDL"},
    {"Monako",                          "+377",       "MC" ,"EUR"},
    {"Moritanya",                       "222",       "MR" ,"MRO"},
    {"Moritus",                         "230",       "MU" ,"MUR"},
    {"Mozambik",                        "258",       "MZ" ,"MZN"},
    {"Myanmar",                         "95",       "MM" ,"MMK"},
    {"Namibya",                         "264",       "NA" ,"NAD"},
    {"Nauru",                           "674",       "NR" ,"AUD"},
    {"Nepal",                           "977",       "NP" ,"NPR"},
    {"Nikaragua",                       "505",       "NI" ,"NIO"},
    {"Nijer",                           "227",       "NE" ,"XOF"},
    {"Nijerya",                         "234",       "NG" ,"NGN"},
    {"Norveç",                          "47",       "NO" ,"NOK"},
    {"Orta Afrika Cumhuriyeti",         "221",       "CF" ,"XOF"},
    {"Özbekistan",                      "998",       "UZ" ,"UZS"},
    {"Pakistan",                        "92",       "PK" ,"PKR"},
    {"Palau",                           "680",       "PW" ,"USD"},
    {"Panama",                          "+507",       "PA" ,"USD"},
    {"Papua Yeni Gine",                 "675",       "PG" ,"PGK"},
    {"Paraguay",                        "595",       "PY" ,"PYG"},
    {"Peru",                            "+51",       "PE" ,"PEN"},
    {"Polonya",                         "48",       "PL" ,"PLN"},
    {"Portekiz",                        "351",       "PT" ,"EUR"},
    {"Romanya",                         "40",       "RO" ,"RON"},
    {"Ruanda",                          "250",       "RW" ,"RWF"},
    {"Rusya Federasyonu",               "7",       "RU" ,"RUB"},
    {"Saint Kitts ve Nevis",            "+1-869",       "KN" ,"XCD"},
    {"Saint Lucia",                     "1-758",       "LC" ,"XCD"},
    {"Saint Vincent ve Grenadinler",    "+1-784",       "VC" ,"XCD"},
    {"Samoa",                           "685",       "WS" ,"WST"},
    {"San Marino",                      "378",       "SM" ,"EUR"},
    {"Sao Tome ve Principe",            "239",       "ST" ,"STD"},
    {"Senegal",                         "221",       "SN" ,"XOF"},
    {"Seyşeller",                       "248",       "SC" ,"SCR"},
    {"Sırbistan",                       "381",       "RS" ,"CSD"},
    {"Sierra Leone",                    "232",       "WAL" ,"SLL"},
    {"Singapur",                        "+65",       "SG" ,"SGD"},
    {"Slovakya",                        "421",       "SK" ,"EUR"},
    {"Slovenya",                        "386",       "SI" ,"EUR"},
    {"Solomon Adaları",                 "677",       "SB" ,"SBD"},
    {"Somali",                          "252",       "SO" ,"SOS"},
    {"Somaliland",                      "252",       "" ,"SLSH"},
    {"Sri Lanka",                       "94",       "LK" ,"LKR"},
    {"Sudan",                           "249",       "SD" ,"SDG"},
    {"Surinam",                         "597",       "SR" ,"SRD"},
    {"Suudi Arabistan",                 "966",       "SA" ,"SAR"},
    {"Suriye",                          "963",       "SY" ,"SYP"},
    {"Svaziland",                       "268",       "SZ" ,"SZL"},
    {"Şili",                            "+56",       "CL" ,"CLP"},
    {"Tacikistan",                      "992",       "TJ" ,"TJS"},
    {"Tanzanya",                        "255",       "TZ" ,"TZS"},
    {"Tayland",                         "+66",       "TH" ,"THB"},
    {"Tayvan",                          "886",       "TW" ,"TWD"},
    {"Togo",                            "228",       "TG" ,"XOF"},
    {"Tonga",                           "676",       "TO" ,"TOP"},
    {"Transdinyester",                  "373",       "PR" ,"PRB"},
    {"Trinidad ve Tobago",              "1-868",     "TT" ,"TTD"},
    {"Tunus",                           "216",       "TN" ,"TND"},
    {"Tuvalu",                          "688",       "TV" ,"AUD"},
    {"Türkiye",                         "90",        "TR" ,"TL"},
    {"Türkmenistan",                    "993",       "TM" ,"TMT"},
    {"Uganda",                          "256",       "UG" ,"UGX"},
    {"Ukrayna",                         "380",       "UA" ,"UAH"},
    {"Umman",                           "968",       "OM" ,"OMR"},
    {"Uruguay",                         "598",       "UY" ,"UYU"},
    {"Ürdün",                           "962",       "JO" ,"JOD"},
    {"Vanuatu",                         "678",       "VU" ,"VUV"},
    {"Vatikan",                         "39",       "VA" ,"EUR"},
    {"Venezuela",                       "58",       "VE" ,"VEF"},
    {"Vietnam",                         "84",       "VN" ,"VND"},
    {"Yemen",                           "967",       "YE" ,"YER"},
    {"Yeni Zelanda",                    "64",       "NZ" ,"NZD"},
    {"Yeşil Burun",                     "238",       "CV" ,"CVE"},
    {"Yunanistan",                      "30",       "GR" ,"EUR"},
    {"Zambiya",                         "260",       "ZM" ,"ZMK"},
    {"Zimbabve",                        "+263",       "ZW" ,"ZWD"},
    {"","","",""                     }};


#endif // ULKELER_H




