#ifndef UNVANLAR_H
#define UNVANLAR_H

const char * unvanlar[][1] = {
    {"Prof.Dr."},
    {"Dr."},
    {"Doç.Dr."},
    {"Yrd.Doç.Dr."},
    {"Özel Kalem Müdürü"},
    {"Vali"},
    {"Hakim"},
    {"Sayıştay Denetçisi"},
    {"Spk Uzmanı"},
    {"Rekabet Kurumu Uzmanı"},
    {"Epdk Uzmanı"},
    {"Başbakanlık Müfettişi"},
    {"Hazine Uzmanı"},
    {"Diyanet İşl. Başk.Müf "},
    {"Devlet Personel Uzmanı "},
    {"Başbakanlık Uzmanı"},
    {"Milli Emlak Denetmeni "},
    {"Muhasebe Denetmeni "},
    {"DPT Uzmanı "},
    {"Hazine Kontrolörü "},
    {"Bağımsız Genel Md. Müf "},
    {"Gümrük Müfettişi "},
    {"Masak Uzmanı "},
    {"Devlet Malları Uzmanı "},
    {"Devlet Gelir Uzmanı "},
    {"Devlet Bütçe Uzmanı "},
    {"Muhasebat Kontrolörü "},
    {"Gelirler Kontrolörü "},
    {"Maliye Müfettişi "},
    {"Hesap Uzmanı"},
    {"Telekomünikasyon Uzmanı "},
    {"Kamu İhale Uzmanı "},
    {"BDDK Murakıp ve Uzmanı "},
    {"Kaymakam"},
    {"Smmm"},
    {"Ymm"},
    {"Müdür"},
    {"Genel Müdür"},
    {"Hemşire"},
    {"Baş Hemşire"},
    {"Hasta Bakıcı"},
    {"Şef"},
    {"Araştırmacı"},
    {"Emniyet Müdürü"},
    {"Yazı İşleri Müdürü"},
    {"İdari ve Mali İşler Müdürü"},
    {""}
};

#endif // UNVANLAR_H
