#ifndef VERGI_DAIRELERI_H
#define VERGI_DAIRELERI_H

/***************************************************


        Kayitlar eklenirken alfabetik siraya dikkat edilmeli


**************************************************/

const char * vergi_daireleri[][2] = {
    {"Adana","Ziyapaşa"},
    {"Adana","Yüreğir"},
    {"Adana","Beşocak"},
    {"Adana","Çukurova"},
    {"Adana","Seyhan"},
    {"Adana","Karataş"},
    {"Adana","Kozan"},
    {"Adana","Ceyhan"},
    {"Adıyaman","Kahta"},
    {"Adıyaman","Besni"},
    {"Adıyaman","Çelikhan"},
    {"Adıyaman","Gölbaşı"},
    {"Adıyaman","Samsat"},
    {"Adıyaman","Gerger"},
    {"Adıyaman","Tut"},
    {"Adıyaman","Sincik"},
    {"Afyon","Bolvadin"},
    {"Afyon","Çay"},
    {"Afyon","Dinar"},
    {"Afyon","Emirdağ"},
    {"Afyon","Kocatepe"},
    {"Afyon","Sandıklı"},
    {"Ağrı","Ağrı"},
    {"Ağrı","Doğubeyazıt"},
    {"Ağrı","Diyadin"},
    {"Ağrı","Taşlıçay"},
    {"Ağrı","Hamur"},
    {"Ağrı","Patnos"},
    {"Ağrı","Tutak"},
    {"Ağrı","Eleşkirt"},
    {"Aksaray","Aksaray"},
    {"Ankara","Ankara  Başkanlığı"},
    {"Ankara","Başkent"},
    {"Ankara","Beypazarı"},
    {"Ankara","Cumhuriyet"},
    {"Ankara","Çankaya"},
    {"Ankara","Çubuk"},
    {"Ankara","Dışkapı"},
    {"Ankara","Dikimevi"},
    {"Ankara","Doğanbey"},
    {"Ankara","Elmadağ"},
    {"Ankara","Etimesgut"},
    {"Ankara","Gölbaşı"},
    {"Ankara","Haymana"},
    {"Ankara","Hitit  Başkanlığı"},
    {"Ankara","Kavaklıdere  Başkanlığı"},
    {"Ankara","Keçiören"},
    {"Ankara","Maltepe"},
    {"Ankara","Mithatpaşa"},
    {"Ankara","Ostim  Başkanlığı"},
    {"Ankara","Polatlı "},
    {"Ankara","Seymenler"},
    {"Ankara","Sincan"},
    {"Ankara","Ulus"},
    {"Ankara","Ulusite"},
    {"Ankara","Yahya Galip"},
    {"Ankara","Yeğenbey"},
    {"Ankara","Yenimahalle"},
    {"Antalya","Kurumlar"},
    {"Antalya","Üçkapılar"},
    {"Antalya","Düden"},
    {"Antalya","Kalekapı"},
    {"Antalya","Muratpaşa"},
    {"Antalya","Alanya"},
    {"Antalya","Manavgat"},
    {"Antalya","Serik"},
    {"Antalya","Kemer"},
    {"Antalya","Kumluca"},
    {"Antalya","Elmalı"},
    {"Amasya","Göynücek"},
    {"Amasya","Gümüşhacıköy"},
    {"Amasya","Gümüşhacıköy"},
    {"Amasya","Hamamözü"},
    {"Amasya","Merzifon"},
    {"Amasya","Merzifon"},
    {"Amasya","Suluova"},
    {"Amasya","Suluova"},
    {"Amasya","Taşova"},
    {"Amasya","Taşova"},
    {"Ardahan","Ardahan"},
    {"Ardahan","Çıldır"},
    {"Ardahan","Damal"},
    {"Ardahan","Göle"},
    {"Ardahan","Hanak"},
    {"Ardahan","Posof"},
    {"Artvin","Artvin"},
    {"Artvin","Hopa"},
    {"Artvin","Arhavi"},
    {"Artvin","Ardanuç"},
    {"Artvin","Yusufeli"},
    {"Artvin","Borçka"},
    {"Artvin","Murgul"},
    {"Artvin","Şavşat"},
    {"Aydın","Çine"},
    {"Aydın","Didim"},
    {"Aydın","Efeler"},
    {"Aydın","Germencik"},
    {"Aydın","Kuşadası"},
    {"Aydın","Nazilli"},
    {"Aydın","Söke"},
    {"Balıkesir","Balya "},
    {"Balıkesir","Gömeç "},
    {"Balıkesir","Havran "},
    {"Balıkesir","İvrindi "},
    {"Balıkesir","Kepsut "},
    {"Balıkesir","Manyas "},
    {"Balıkesir","Marmara "},
    {"Balıkesir","Savaştepe "},
    {"Bartın","Bartın"},
    {"Batman","Batman"},
    {"Bayburt","Bayburt"},
    {"Bayburt","Aydıntepe"},
    {"Bayburt","Demirözü"},
    {"Bilecik","Bilecik"},
    {"Bilecik","Bozüyük"},
    {"Bingöl","Adaklı"},
    {"Bingöl","Genç"},
    {"Bingöl","Karlıova"},
    {"Bingöl","Kiğı"},
    {"Bingöl","Solhan"},
    {"Bingöl","Yayladere"},
    {"Bingöl","Yedisu"},
    {"Bitlis","Tatvan"},
    {"Bitlis","Tatvan"},
    {"Bitlis","Ahlat"},
    {"Bitlis","Adilcevaz"},
    {"Bitlis","Mutki"},
    {"Bitlis","Hizan"},
    {"Bitlis","Güroymak"},
    {"Bolu","Bolu"},
    {"Bolu","Gerede"},
    {"Burdur","Ağlasun"},
    {"Burdur","Altınyayla"},
    {"Burdur","Bucak"},
    {"Burdur","Çavdır"},
    {"Burdur","Çeltikçi"},
    {"Burdur","Gölhisar"},
    {"Burdur","Karamanlı"},
    {"Burdur","Kemer"},
    {"Burdur","Yeşilova"},
    {"Burdur","Tefenni"},
    {"Burdur","Bucak "},
    {"Bursa","Yıldırım"},
    {"Bursa","Uludağ"},
    {"Bursa","Osmangazi"},
    {"Bursa","Gökdere"},
    {"Bursa","Çekirge"},
    {"Bursa","Yeşil"},
    {"Bursa","Yeşil V.D. Md. Otasansit T.Ş."},
    {"Bursa","Ertuğrulgazi"},
    {"Bursa","Nilüfer"},
    {"Bursa","Gemlik"},
    {"Bursa","Mudanya"},
    {"Bursa","İnegöl"},
    {"Bursa","İznik"},
    {"Bursa","Orhangazi"},
    {"Bursa","Karacabey"},
    {"Bursa","Mustafakemalpaşa"},
    {"Bursa","Yenişehir"},
    {"Bursa","Keles"},
    {"Bursa","Orhaneli"},
    {"Bursa","Büyükorhan"},
    {"Bursa","Harmancık"},
    {"Çanakkale","Gelibolu"},
    {"Çanakkale","Çanakkale"},
    {"Çanakkale","Çan"},
    {"Çanakkale","Biga"},
    {"Çankırı","Çankırı"},
    {"Çorum","Bayat"},
    {"Çorum","Boğazkale"},
    {"Çorum","Dodurga"},
    {"Çorum","İskilip"},
    {"Çorum","Kargı"},
    {"Çorum","Laçin"},
    {"Çorum","Mecitözü"},
    {"Çorum","Oğuzlar"},
    {"Çorum","Ortaköy"},
    {"Çorum","Osmancık"},
    {"Çorum","Sungurlu"},
    {"Çorum","Uğurludağ"},
    {"Çorum","Sungurlu"},
    {"Denizli","Acıpayam"},
    {"Denizli","Sarayköy"},
    {"Denizli","Tavas"},
    {"Denizli","Çivril"},
    {"Denizli","Çal"},
    {"Denizli","Buldan"},
    {"Denizli","Beyağaç"},
    {"Denizli","Güney"},
    {"Denizli","Akköy"},
    {"Denizli","Honaz"},
    {"Denizli","Kale"},
    {"Denizli","Serinhisar"},
    {"Denizli","Çardak"},
    {"Denizli","Bozkurt"},
    {"Denizli","Babadağ"},
    {"Denizli","Baklan"},
    {"Denizli","Bekilli"},
    {"Denizli","Çameli"},
    {"Diyarbakır","Gökalp"},
    {"Diyarbakır","Cahit Sıtkı Tarancı"},
    {"Diyarbakır","Süleyman Nazif"},
    {"Düzce","Düzce"},
    {"Düzce","Akçakoca"},
    {"Düzce","Cumayeri"},
    {"Düzce","Çilimli"},
    {"Düzce","Gölyaka"},
    {"Düzce","Gümüşova"},
    {"Düzce","Kaynaşlı"},
    {"Düzce","Yığılca"},
    {"Elazığ","Harput"},
    {"Elazığ","Hazar"},
    {"Elazığ","Kovancılar"},
    {"Elazığ","Arıcak"},
    {"Elazığ","Alacakaya"},
    {"Elazığ","Palu"},
    {"Elazığ","Maden"},
    {"Elazığ","Sivrice"},
    {"Elazığ","Baskil"},
    {"Elazığ","Keban"},
    {"Elazığ","Ağın"},
    {"Erzincan","Erzincan"},
    {"Erzincan","Çayırlı"},
    {"Erzincan","İliç"},
    {"Erzincan","Kemah"},
    {"Erzincan","Kemaliye"},
    {"Erzincan","Refahiye"},
    {"Erzincan","Tercan"},
    {"Erzincan","Üzümlü"},
    {"Erzincan","Otlukbeli"},
    {"Erzurum","Aziziye"},
    {"Erzurum","Kazım Karabaekir"},
    {"Erzurum","Aşkale"},
    {"Erzurum","Çat"},
    {"Erzurum","Hınıs"},
    {"Erzurum","Horasan"},
    {"Erzurum","Aziziye (Ilıca)"},
    {"Erzurum","İspir"},
    {"Erzurum","Karaçoban"},
    {"Erzurum","Karayazı"},
    {"Erzurum","Köprüköy"},
    {"Erzurum","Narman"},
    {"Erzurum","Olur"},
    {"Erzurum","Oltu"},
    {"Erzurum","Pasinler"},
    {"Erzurum","Pazaryolu"},
    {"Erzurum","Şenkaya"},
    {"Erzurum","Tekman"},
    {"Erzurum","Tortum"},
    {"Erzurum","Uzundere"},
    {"Eskişehir","Yunus Emre"},
    {"Eskişehir","2 Eylül"},
    {"Eskişehir","Battalgazi"},
    {"Eskişehir","Taşbaşı"},
    {"Eskişehir","Çifteler"},
    {"Eskişehir","Sivrihisar"},
    {"Eskişehir","Mihalıççık"},
    {"Eskişehir","Mahmudiye"},
    {"Eskişehir","Seyitgazi"},
    {"Eskişehir","Sarıcakaya"},
    {"Eskişehir","Alpu"},
    {"Eskişehir","Beylikova"},
    {"Eskişehir","Günyüzü"},
    {"Eskişehir","İnönü"},
    {"Eskişehir","Han"},
    {"Eskişehir","Mihalgazi"},
    {"Gaziantep","Gaziantep  Başkanlığı"},
    {"Gaziantep","Gazikent"},
    {"Gaziantep","Şahinbey"},
    {"Gaziantep","Kozanlı"},
    {"Gaziantep","Şehitkamil"},
    {"Gaziantep","İslahiye"},
    {"Gaziantep","Suburcu"},
    {"Gaziantep","Nizip"},
    {"Giresun","Giresun"},
    {"Giresun","Bulancak"},
    {"Gümüşhane","Gümüşhane"},
    {"Hakkari","Hakkari"},
    {"Hatay","23 Temmuz"},
    {"Hatay","Şükrü Kanatlı"},
    {"Hatay","Antakya"},
    {"Hatay","Akdeniz"},
    {"Hatay","Asım Gündüz"},
    {"Hatay","Sahil"},
    {"Hatay","Dörtyol"},
    {"Hatay","Kırıkhan"},
    {"Hatay","Reyhanlı"},
    {"Hatay","Samandağ"},
    {"Hatay","Hassa"},
    {"Hatay","Altınözü"},
    {"Hatay","Yayladağı"},
    {"Isparta","Davraz"},
    {"Isparta","Eğirdir"},
    {"Isparta","Yalvaç"},
    {"İstanbul","Adalar "},
    {"İstanbul","Anadolu Kurumlar  Başkanlığı"},
    {"İstanbul","Atışalanı "},
    {"İstanbul","Avcılar "},
    {"İstanbul","Bakırköy "},
    {"İstanbul","Bayrampaşa "},
    {"İstanbul","Beşiktaş "},
    {"İstanbul","Beyazıt "},
    {"İstanbul","Beykoz "},
    {"İstanbul","Beylikdüzü "},
    {"İstanbul","Beyoğlu  Başkanlığı"},
    {"İstanbul","Boğaziçi Kurumlar "},
    {"İstanbul","Büyükçekmece "},
    {"İstanbul","Çapa "},
    {"İstanbul","Çatalca "},
    {"İstanbul","Davutpaşa "},
    {"İstanbul","Dış Ticaret "},
    {"İstanbul","Erenköy "},
    {"İstanbul","Esenler "},
    {"İstanbul","Fatih "},
    {"İstanbul","Galata "},
    {"İstanbul","Gaziosmanpaşa "},
    {"İstanbul","Göztepe "},
    {"İstanbul","Güneşli "},
    {"İstanbul","Güngören "},
    {"İstanbul","Halkalı  Başkanlığı"},
    {"İstanbul","Hisar "},
    {"İstanbul","Hocapaşa "},
    {"İstanbul","İkitelli "},
    {"İstanbul","Kadıköy "},
    {"İstanbul","Kağıthane "},
    {"İstanbul","Kartal "},
    {"İstanbul","Kasımpaşa "},
    {"İstanbul","Kocamustafapaşa "},
    {"İstanbul","Kocasinan "},
    {"İstanbul","Kozyatağı "},
    {"İstanbul","Küçükçekmece "},
    {"İstanbul","Küçükköy "},
    {"İstanbul","Küçükyalı "},
    {"İstanbul","Laleli "},
    {"İstanbul","Marmara Kurumlar  Başkanlığı"},
    {"İstanbul","Maslak "},
    {"İstanbul","Mecidiyeköy "},
    {"İstanbul","Mercan "},
    {"İstanbul","Merter "},
    {"İstanbul","Mevlanakapı "},
    {"İstanbul","Nak. Vasıta. Ataköy T.Ş."},
    {"İstanbul","Nak. Vasıta. Bağlarbaşı T.Ş."},
    {"İstanbul","Nak. Vasıta. Bahçelievler T.Ş."},
    {"İstanbul","Nak. Vasıta. Beylikdüzü T.Ş."},
    {"İstanbul","Nak. Vasıta. Bostancı T.Ş."},
    {"İstanbul","Nak. Vasıta. Büyükçekmece T.Ş."},
    {"İstanbul","Nak. Vasıta. Çatalca T.Ş."},
    {"İstanbul","Nak. Vasıta. Esentepe T.Ş."},
    {"İstanbul","Nak. Vasıta. Fevzi Çakmak T.Ş."},
    {"İstanbul","Nak. Vasıta. Karaköy T.Ş."},
    {"İstanbul","Nak. Vasıta. Merdivenköy T.Ş."},
    {"İstanbul","Nak. Vasıta. Moda T.Ş."},
    {"İstanbul","Nak. Vasıta. Silivri T.Ş."},
    {"İstanbul","Nak. Vasıta. Şile T.Ş."},
    {"İstanbul","Nak. Vasıta. Topkapı T.Ş."},
    {"İstanbul","Nak. Vasıta. Tuzla T.Ş."},
    {"İstanbul","Nakil Vasıtaları"},
    {"İstanbul","Nuruosmaniye  Başkanlığı"},
    {"İstanbul","Pendik "},
    {"İstanbul","Rami "},
    {"İstanbul","Rıhtım "},
    {"İstanbul","Sarıgazi "},
    {"İstanbul","Sarıyer "},
    {"İstanbul","Silivri "},
    {"İstanbul","Sultanahmet "},
    {"İstanbul","Sultanbeyli "},
    {"İstanbul","Süleymaniye "},
    {"İstanbul","Şile "},
    {"İstanbul","Şişli "},
    {"İstanbul","Tuna "},
    {"İstanbul","Tuzla "},
    {"İstanbul","Ulaştırma "},
    {"İstanbul","Ümraniye "},
    {"İstanbul","Üsküdar "},
    {"İstanbul","Yakacık "},
    {"İstanbul","Yeditepe "},
    {"İstanbul","Yenibosna "},
    {"İstanbul","Zeytinburnu "},
    {"İstanbul","Zincirlikuyu "},
    {"İzmir","Aliağa"},
    {"İzmir","Bayındır"},
    {"İzmir","Bergama"},
    {"İzmir","Çiğli"},
    {"İzmir","Karşıyaka"},
    {"İzmir","Gaziemir"},
    {"İzmir","Bornova"},
    {"İzmir","Çakabey"},
    {"İzmir","Hasan Tahsin"},
    {"İzmir","Kordon"},
    {"İzmir","Ege"},
    {"İzmir","Konak"},
    {"İzmir","Şirinyer"},
    {"İzmir","Kemeraltı"},
    {"İzmir","Kadifekale"},
    {"İzmir","Basmane"},
    {"İzmir","Taşıtlar"},
    {"İzmir","9 Eylül"},
    {"İzmir","Yamanlar"},
    {"İzmir","Belkahve"},
    {"İzmir","Çeşme"},
    {"İzmir","Kemalpaşa"},
    {"İzmir","Kiraz"},
    {"İzmir","Kınık"},
    {"İzmir","Menderes"},
    {"İzmir","Menemen"},
    {"İzmir","Ödemiş"},
    {"İzmir","Selçuk"},
    {"İzmir","Tire"},
    {"İzmir","Torbalı"},
    {"İzmir","Urla"},
    {"İzmir","Balçova"},
    {"Mardin","Mardin"},
    {"Mardin","Kızıltepe"},
    {"Mardin","Nusaybibn"},
    {"Mardin","Mazıdağı"},
    {"Mardin","Derik"},
    {"Mardin","Ömerli"},
    {"Mardin","Yeşilli"},
    {"Mardin","Dargeçit"},
    {"Mardin","Savur"},
    {"Mardin","Midyat"},
    {"Mersin","Uray"},
    {"Mersin","Toros"},
    {"Mersin","Tarsus Şehitkerim"},
    {"Mersin","Tarsus Kızılmurat"},
    {"Mersin","Silifke"},
    {"Mersin","Mersin  Başkanlığı"},
    {"Mersin","Liman"},
    {"Mersin","İstiklal"},
    {"Mersin","Erdemli"},
    {"Mersin","Anamur"},
    {"Osmaniye","Osmaniye"},
    {"Osmaniye","Kadirli"},
    {"Osmaniye","Bahçe"},
    {"Osmaniye","Düziçi"},
    {"Osmaniye","Hasanbeyli"},
    {"Osmaniye","Sumbas"},
    {"Osmaniye","Toprakkale"},
    {"Kahramanmaraş","Aksu"},
    {"Kahramanmaraş","Aslanbey"},
    {"Kahramanmaraş","Elbistan"},
    {"Kahramanmaraş","Pazarcık"},
    {"Kahramanmaraş","Afşin"},
    {"Karabük","Karabük"},
    {"Karabük","Eflani"},
    {"Karabük","Eskipazar"},
    {"Karabük","Ovacık"},
    {"Karabük","Safranbolu"},
    {"Karabük","Safranbolu"},
    {"Karabük","Yenice"},
    {"Kars","Kars"},
    {"Kastamonu","Tosya"},
    {"Kastamonu","Taşköprü"},
    {"Kastamonu","Kastamonu"},
    {"Kayseri","Gevher Nesibe"},
    {"Kayseri","Erciyes"},
    {"Kayseri","Mimarsinan"},
    {"Kayseri","Kaleönü"},
    {"Kayseri","Bünyan"},
    {"Kayseri","Develi"},
    {"Kayseri","Pınarbaşı"},
    {"Kayseri","Akkışla"},
    {"Kayseri","Hacılar"},
    {"Kayseri","İncesu"},
    {"Kayseri","Yahyalı"},
    {"Kayseri","Tomarza"},
    {"Kayseri","Yeşilhisar"},
    {"Kayseri","Sarıoğlan"},
    {"Kayseri","Felahiye"},
    {"Kayseri","Sarız"},
    {"Kayseri","Özvatan"},
    {"Kırıkkale","Kartaltepe"},
    {"Kırıkkale","Irmak"},
    {"Kırıkkale","Keskin"},
    {"Kırıkkale","Delice"},
    {"Kırıkkale","Sulakyurt"},
    {"Kırıkkale","Balışeyh"},
    {"Kırıkkale","Çelebi"},
    {"Kırıkkale","Karakeçeli"},
    {"Kırklareli","Kırklareli"},
    {"Kırklareli","Babaeski"},
    {"Kırklareli","Lüleburgaz"},
    {"Kırşehir","Kırşehir"},
    {"Kilis","Kilis"},
    {"Kocaeli","Kocaeli  Başkanlığı"},
    {"Kocaeli","Tepecik"},
    {"Kocaeli","Alemdar"},
    {"Kocaeli","Acısu"},
    {"Kocaeli","Derince"},
    {"Kocaeli","Uluçınar"},
    {"Kocaeli","İlyasbey"},
    {"Kocaeli","Gölcük"},
    {"Kocaeli","Karamürsel"},
    {"Kocaeli","Körfez"},
    {"Konya","Alaaddin"},
    {"Konya","Meram"},
    {"Konya","Mevlana"},
    {"Konya","Selçuk"},
    {"Konya","Akşehir"},
    {"Konya","Beyşehir"},
    {"Konya","Cihanbeyli"},
    {"Konya","Çumra"},
    {"Konya","Ereğli"},
    {"Konya","Ilgın"},
    {"Konya","Kulu"},
    {"Konya","Seydişehir"},
    {"Kütahya","30 Ağustos"},
    {"Kütahya","Çinili"},
    {"Kütahya","Altıntaş"},
    {"Kütahya","Aslanpaşa"},
    {"Kütahya","Çavdarhisar"},
    {"Kütahya","Domaniç"},
    {"Kütahya","Dumlupınar"},
    {"Kütahya","Emet"},
    {"Kütahya","Emet"},
    {"Kütahya","Hisarcık"},
    {"Kütahya","Gediz"},
    {"Kütahya","Gediz"},
    {"Kütahya","Pazarlar"},
    {"Kütahya","Simav"},
    {"Kütahya","Simav"},
    {"Kütahya","Şaphane"},
    {"Kütahya","Tavşanlı"},
    {"Kütahya","Tavşanlı"},
    {"Malatya","Fırat"},
    {"Malatya","Beydağı"},
    {"Manisa","Akhisar"},
    {"Manisa","Alaşehir"},
    {"Manisa","Demirci"},
    {"Manisa","Gördes"},
    {"Manisa","Kırkağaç"},
    {"Manisa","Kula"},
    {"Manisa","Salihli Adil Oral"},
    {"Manisa","Sarıgöl"},
    {"Manisa","Saruhanlı"},
    {"Manisa","Soma"},
    {"Manisa","Turgutlu"},
    {"Manisa","Alaybey"},
    {"Iğdır","Iğdır"},
    {"Iğdır","Karakoyunlu"},
    {"Iğdır","Tuzluca"},
    {"Iğdır","Aralık"},
    {"Muğla","Muğla"},
    {"Muğla","Bodrum"},
    {"Muğla","Fethiye"},
    {"Muğla","Köyceğiz"},
    {"Muğla","Milas"},
    {"Muğla","Marmaris"},
    {"Muğla","Yatağan"},
    {"Muğla","Ortaca"},
    {"Muğla","Dalaman"},
    {"Muğla","Datça"},
    {"Muğla","Ula"},
    {"Muğla","Kavaklıdere"},
    {"Muş","Muş"},
    {"Nevşehir","Nevşehir"},
    {"Nevşehir","Acıgöl"},
    {"Nevşehir","Avanos"},
    {"Nevşehir","Derinkuyu"},
    {"Nevşehir","Gülşehir"},
    {"Nevşehir","Hacıbektaş"},
    {"Nevşehir","Kozaklı"},
    {"Nevşehir","Ürgüp"},
    {"Niğde","Niğde"},
    {"Niğde","Bor"},
    {"Niğde","Bor"},
    {"Niğde","Altunhisar"},
    {"Niğde","Çamardı"},
    {"Niğde","Çiftlik"},
    {"Niğde","Ulukışla"},
    {"Ordu","Boztepe"},
    {"Ordu","Fatsa"},
    {"Ordu","Ünye"},
    {"Rize","Ardeşen"},
    {"Rize","Çayeli"},
    {"Rize","Kaçkar"},
    {"Rize","Pazar"},
    {"Rize","Yeşilçay"},
    {"Sakarya","Sakarya  Başkanlığı"},
    {"Sakarya","Ali Fuat Cebesoy"},
    {"Sakarya","Gümrükönü"},
    {"Sakarya","Akyazı"},
    {"Sakarya","Geyve"},
    {"Sakarya","Hendek"},
    {"Sakarya","Karasu"},
    {"Samsun","Samsun  Başkanlığı"},
    {"Samsun","Gaziler"},
    {"Samsun","Ondokuzmayıs"},
    {"Samsun","Zafer"},
    {"Samsun","Bafra"},
    {"Samsun","Çarşamba"},
    {"Samsun","Havza"},
    {"Samsun","Terme"},
    {"Siirt","Siirt"},
    {"Sinop","Sinop"},
    {"Sinop","Boyabat"},
    {"Sivas","Kale"},
    {"Sivas","Site"},
    {"Sivas","Şarkışla"},
    {"Tekirdağ","Tekirdağ  Başkanlığı"},
    {"Tekirdağ","Çorlu"},
    {"Tekirdağ","Çerkezköy"},
    {"Tekirdağ","Malkara"},
    {"Tekirdağ","Hayrabolu"},
    {"Tekirdağ","Muratlı"},
    {"Tekirdağ","Namık Kemal"},
    {"Tekirdağ","Süleymanpaşa"},
    {"Tokat","Tokat"},
    {"Tokat","Erbaa"},
    {"Tokat","Niksar"},
    {"Tokat","Turhal"},
    {"Tokat","Zile"},
    {"Trabzon","Trabzon  Başkanlığı"},
    {"Trabzon","Karadeniz"},
    {"Trabzon","Hızırbey"},
    {"Trabzon","Akçaabat"},
    {"Trabzon","Of"},
    {"Trabzon","Vakfıkebir"},
    {"Tunceli","Tunceli"},
    {"Şanlıurfa","Şanlıurfa  Başkanlığı"},
    {"Şanlıurfa","Şehitlik"},
    {"Şanlıurfa","Birecik"},
    {"Şanlıurfa","Siverek"},
    {"Şanlıurfa","Viranşehir"},
    {"Şırnak","Şırnak"},
    {"Şırnak","Cizre"},
    {"Şırnak","Silopi"},
    {"Uşak","Uşak"},
    {"Uşak","Banaz"},
    {"Uşak","Eşme"},
    {"Van","Van"},
    {"Van","Erciş"},
    {"Yalova","Yalova"},
    {"Yalova","Armutlu"},
    {"Yalova","Altınova"},
    {"Yalova","Çınarcık"},
    {"Yozgat","Yozgat"},
    {"Yozgat","Boğazlıyan"},
    {"Yozgat","Sorgun"},
    {"Yozgat","Yerköy"},
    {"Zonguldak","Zonguldak  Başkanlığı"},
    {"Zonguldak","Çaycuma"},
    {"Zonguldak","Devrek"},
    {"Zonguldak","Karaelmas"},
    {"Zonguldak","Kdz Ereğli"},
    {"",""}};



#endif // VERGI_DAIRELERI_H
