; Script generated by the HM NIS Edit Script Wizard.

!define ADAK_PRG_DIR "K9"
!define ADAK_PRG_EXE "K9.exe"
!define ADAK_PRG_ICON "K9_logo.ico"
!define ADAK_PRG_NAME "K9 - Ticari Paket"
!define PRODUCT_VERSION "x.yy"

!include "..\NSIS_SCRIPT.nsi"
